Create a complete React web app UI for "EcoFungi Trace" — a fungi-powered plastic 
degradation tracking platform built by 11-year-old students. 

DESIGN STYLE:
- Modern web app with a playful, child-friendly feel
- Environmental color palette: greens (#2D6A4F, #52B788, #95D5B2, #D8F3DC), 
  earthy browns (#6B4226), warm yellows (#F4D35E), clean whites
- Rounded corners everywhere (border-radius: 16-24px for cards, 12px for buttons)
- Big friendly typography (Inter or Nunito font)
- Generous whitespace, card-based layout
- Emoji accents: 🍄 🌿 ♻️ 🌍 used sparingly as visual elements
- Image placeholders styled as rounded rectangles with green tint 
  (labeled "AI image: mushroom growing on plastic" etc.) — all images will be 
  generated by AI later
- NO gradients on backgrounds, flat colored sections instead
- Mobile-first but desktop-friendly (max-width: 1200px centered)

PAGES TO GENERATE (each as a separate frame/component):

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE 1: Home / Landing (route: /)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NAVBAR:
- Logo: "🍄 EcoFungi Trace" in green, bold
- Links: "Verify Batch" | "Request Kit" | "Admin" (small, top right)
- White background, subtle bottom border

HERO SECTION:
- Full-width section, light green background (#D8F3DC)
- Large heading: "Fungi That Save the Planet 🌍"
- Subheading: "Every kit, one less step of plastic"
- Image placeholder (large, centered): rounded rect, label "AI image: 
  oyster mushroom on colorful plastic background"
- Two CTA buttons: "[🍄 Request a Kit]" (green filled) + 
  "[How does it work? ▾]" (white outlined)

BENEFITS SECTION:
- White background
- Section title: "Why EcoFungi?"
- 3 cards in a row, each with:
  * Large emoji (♻️ / 🌿 / 🔗)
  * Bold title ("Degrades Plastic" / "100% Natural" / "Blockchain Verified")
  * 2-line description
  * Light green card background

HOW IT WORKS SECTION:
- Light beige background (#F8F4EF)
- Section title: "The Science of Mycoremediation"
- 2 columns: left = image placeholder ("AI image: diagram of fungi eating plastic"), 
  right = 3 numbered steps with icons and descriptions
- Step 1: "The fungus grows 🍄" | Step 2: "Enzymes break down plastic ⚗️" | 
  Step 3: "Clean soil! 🌱"

CHATBOT WIDGET:
- Fixed bottom-right floating button: round green button "🤖 Ask EcoBot"
- When expanded: chat window (300x400px) floating card
  * Header: "EcoBot 🤖" with green bar, close button
  * Chat area: 2 example messages (user bubble green right, bot bubble gray left)
  * User message: "How does the fungus eat plastic?"
  * Bot response: "Great question! Oyster mushrooms produce special enzymes called 
    laccases that break down plastic polymers..."
  * Suggestion chips below: "Tell me more" | "Which plastics?" | "Is it safe?"
  * Input bar at bottom with send button
  * Note in comment: "// Connect to OpenRouter API - model: google/gemini-flash-1.5"

FOOTER:
- Dark green background (#1B4332)
- Logo + tagline + "Made by 11-year-old students ❤️"
- Links: GitHub | Polygonscan | Firebase

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE 2: Traceability (route: /trazabilidad)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- White page, centered layout max-width 700px
- Page title: "🔍 Verify Your Batch"
- Large search bar: input "Enter batch ID (e.g. BATCH-2024-001)" + green "Search" button
- RESULT CARD (shown after search):
  * Card header: "Oyster Mushroom Kit 500g — Batch 001" + green badge "Delivered ✓"
  * Image placeholder small left: "AI image: mushroom kit box"
  * Timeline component (vertical, left-aligned dots):
    - Each step: colored circle (green=done, gray=pending) + status label + 
      date + description + blockchain badge
    - Step 1: "Created 🟢" | Jan 15, 2024 | "Batch created at EcoFungi facilities" 
      | [✓ Blockchain 0x1a2b...↗]
    - Step 2: "Packed 🟢" | Jan 17, 2024 | [...] | [✓ 0x3c4d...↗]
    - Step 3: "Shipped 🟢" | Jan 19, 2024 | [...] | [✓ 0x5e6f...↗]
    - Step 4: "Delivered 🟢" | Jan 22, 2024 | [...] | [✓ 0x7g8h...↗]
  * Blockchain badge style: small pill, green background, "✓ Verified on Polygon" 
    text, external link icon
  * Note in comment: "// Fetch from Firestore: db.collection('batches').doc(id)"
  * Note: "// Each txHash links to: https://amoy.polygonscan.com/tx/{hash}"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE 3: Request Kit (route: /request)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Light green page background (#D8F3DC)
- Centered card (max-width 560px), white, rounded corners
- Card header: "🍄 Request Your Mushroom Kit"
- Image placeholder top: "AI image: happy kid holding mushroom kit box"
- Form fields (all rounded, friendly):
  * Full name (text input)
  * Email (email input)
  * Phone (tel input)
  * City (text input)
  * Address (textarea, 3 rows)
  * Quantity (number input, min 1 max 10)
  * Message / Notes (textarea, optional)
  * Submit button: full width, green, "[🍄 Request My Kit →]"
- Success state: replace form with green checkmark card 
  "✓ Request received! #SOL-2024-042 — We'll contact you soon 🌿"
- Note in comment: "// Save to Firestore: db.collection('requests').add(formData)"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE 4: Admin Panel (route: /admin) — protected
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- White sidebar layout: left sidebar (220px) + main content
- SIDEBAR:
  * Logo top
  * Menu items with icons: 🧺 Batches | 📦 Requests | ⚙️ Settings
  * Bottom: user email + logout button
  * Note: "// Firebase Auth: auth.currentUser"

- MAIN CONTENT (Batches view):
  * Header row: "Active Batches" title + "[+ Create Batch]" green button
  * Batch table/card list:
    Each batch card:
    - ID badge (e.g. BATCH-001) | Name | Quantity | Status badge (color-coded:
      "Created"=blue / "Packed"=yellow / "Shipped"=orange / "Delivered"=green)
    - Two action buttons: "[Register Event 🔗]" (records blockchain event) + "[View]"
  * 3 example batch cards visible

- CREATE BATCH MODAL (overlay):
  * Modal card floating centered
  * Title: "New Batch"
  * Fields: Batch name, mushroom type (dropdown), quantity, notes
  * Buttons: [Cancel] [Create + Register on Blockchain 🔗]
  * Note: "// contract.registerEvent(batchId, 'created', description)"
  * Note: "// Save txHash to Firestore after tx.wait()"

- REGISTER EVENT MODAL:
  * Batch ID shown (read only)
  * Current status shown
  * "New status" dropdown: Packed / Shipped / Delivered
  * Description textarea
  * "[Register on Blockchain + Save]" button with loading spinner state
  * Note: "// ethers.js v6: contract.registerEvent(id, status, desc)"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE 5: Admin Login (route: /login)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Full page centered, light green background
- Center card (400px wide):
  * Logo + "Admin Panel" title
  * Email input
  * Password input  
  * "[Login →]" green button
  * Note: "// Firebase: signInWithEmailAndPassword(auth, email, password)"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SHARED COMPONENTS TO GENERATE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Navbar component (used in all public pages)
- Footer component
- ChatBot floating widget
- BlockchainBadge (pill with "✓ Polygon" and external link)
- StatusBadge (colored pill: created/packed/shipped/delivered)
- BatchCard (used in admin list)
- TimelineStep (used in traceability)
- LoadingSpinner (for async blockchain calls)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CODE OUTPUT REQUIREMENTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generate as React JSX components using:
- Tailwind CSS for styling (or plain CSS with the color palette above)
- Functional components with hooks (useState, useEffect)
- React Router v6 for navigation (useNavigate, Link)
- All async calls stubbed as: 
  "// TODO: connect [ServiceName]" with the exact function signature
- No TypeScript (plain JavaScript)
- All image placeholders as <div> with background color + centered label text
- Folder structure: src/pages/ for pages, src/components/ for shared components
- Each file self-contained and importable

Add this comment block at the top of each file that needs external connection:
/*
 * CONNECTIONS NEEDED:
 * - Firebase: import { db, auth } from '../lib/firebase'
 * - Blockchain: import { registerEvent } from '../lib/blockchain'  
 * - AI Chatbot: import { askEcoBot } from '../lib/gemini'
 * See .env.example for required environment variables
 */